### ISSUE TITLE
Lack of callbacks to some important events

### ISSUE THREAD

**Issue by Tomerlm** [dmt195/tiktok-flutter-plugin#6]
Hey, great library you got here :)
I think listening to some callbacks will be beneficial for various use cases: 
- getting the current scroll index
- scrolling back on the first item (in my use case I wanted to implement scroll to refresh for example)

I can create PR for those, though I'm not sure my changes are in line with you style :)

thanks!

**Comment by dmt195** [comment]
Thanks a lot :)

This sounds a lot like a controller that was suggested [in another issue](https://github.com/dmt195/tiktok-flutter-plugin/issues/5). I've been meaning to look at that for some time. If you'd like to have a go yourself I'd definitely incorporate it.

**Comment by Tomerlm** [comment]
Great, I'm trying to push my branch but it seems I don't have permissions, could you help me with that?

**Comment by dmt195** [comment]
You should be able to submit a PR after forking the repo. Although I've given you temp access as a contributor because I'm too trusting!

**Comment by Tomerlm** [comment]
Done! its my first PR ever to an open source, so feel free to correct me for any convention mistakes 🗡️

**Comment by dmt195** [comment]
Nice - thanks for the effort. Don't worry, this is my first active open source repo so it's all good. I'll start to look at the code this evening.

**Comment by theowenyoung** [comment]
Thanks, @Tomerlm, If I'm not wrong, it seems this pr still not implemented the refresh feature?

> scrolling back on the first item (in my use case I wanted to implement scroll to refresh for example)

**Comment by dmt195** [comment]
> Thanks, @Tomerlm, If I'm not wrong, it seems this pr still not implemented the refresh feature?
> 
> > scrolling back on the first item (in my use case I wanted to implement scroll to refresh for example)

Hey @theowenyoung - the callback is in place to trigger your refresh functionality but this library can't do that for you.

**Comment by theowenyoung** [comment]
@dmt195 Thanks for the reply!

When I refreshed, I mean that I want to set the card index to `0`, and replace the whole cards, I suppose  this need that I pass the `cardIndex` to the plugin, I have forked the repo, and add `cardIndex` as a parameter,  it works for me.

I don't know if I should submit this pr to your library?

https://github.com/theowenyoung/tiktok-flutter-plugin/blob/b7d6b92cfe8a6fcd9499def36ad4762d71f15dfa/lib/tiktoklikescroller.dart#L22
